
version: "3"
services:

  action-service:
    build: ../AVCore/RRHH/actions/
    environment:
      - LANG=es_ES
      - PYTHONIOENCODING=utf-8
    ports:
      - "5055:5055"
    entrypoint: "rasa run actions --debug"
    restart: always

  core-service:
    build: ../AVCore/RRHH/
    environment:
      - LANG=es_ES
      - PYTHONIOENCODING=utf-8
    ports:
      - "5006:5006"
    entrypoint: "rasa run -p 5006 --debug"
    restart: always

  nlu-service:
    build: NLU/RRHH/
    environment:
      - LANG=es_ES
      - PYTHONIOENCODING=utf-8
    ports:
      - "5005:5005"
    entrypoint: "rasa run --enable-api --debug"
    restart: always

  duck-service:
    image: "rasa/duckling"
    ports:
      - "8000:8000"
    restart: always

  main-service:
    build: .
    env_file:
      - ../twilio.env
    environment:
      - LANG=es_ES
      - PYTHONIOENCODING=utf-8
    ports:
      - "5060:5060"
    # just keep server alive
    entrypoint: "python AVtest.py"
    restart: always